In [97]:
from __future__ import annotations

import importlib
import sys
from datetime import date
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from matplotlib.colors import LogNorm

pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option('display.max_rows', 500)


config_dir = Path.home() / '.pulsepoint'
sys.path.insert(0, str(config_dir))

from dotenv import load_dotenv

load_dotenv(config_dir / '.env', override=False)
dbfuncs = importlib.import_module('dbfuncs')

In [98]:
def run_query(sql: str) -> pd.DataFrame:
    return dbfuncs.query2df(sql, print_time=True)

In [186]:
run_query("""
select distinct *,
lower(to_hex(sha256(to_utf8(lower(trim(emails)))))) as pii_hashedemail
from iceberg.thirdparty.pii_clean  
where npi='1639530496'
and day='2026-09-28'
order by source, npi, state, profession, specialties
""")

Query executed in 4.173 seconds

,day,source,id,first_name,last_name,addr_1,addr_2,city,state,zip,phone,npi,profession,specialties,emails,hashedemails,datavendor,accountid,pii_hashedemail
0,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,635 NW 88th DRive,,,FL,33069,,1639530496,Nurse/Advanced Practice Nurse,Administration/Management,ahuntguelph@hotmail.com,,MEDSCAPE REGISTRATION,MS,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e
1,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,635 NW 88th DRive,,,FL,33069,,1639530496,Nurse/Advanced Practice Nurse,Diabetes,ahuntguelph@hotmail.com,,MEDSCAPE REGISTRATION,MS,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e
2,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,635 NW 88th DRive,,,FL,33069,,1639530496,Nurse/Advanced Practice Nurse,Geriatrics,ahuntguelph@hotmail.com,,MEDSCAPE REGISTRATION,MS,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e
3,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,MO,63401,,1639530496,Nurse/Advanced Practice Nurse,Administration/Management,iamlabocagrande@gmail.com,,MEDSCAPE REGISTRATION,MS,8a6797263d39bea884055deacac7b26968ae939f3cf2dbd497efa861e0f1c20c
4,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,MO,63401,,1639530496,Nurse/Advanced Practice Nurse,Diabetes,iamlabocagrande@gmail.com,,MEDSCAPE REGISTRATION,MS,8a6797263d39bea884055deacac7b26968ae939f3cf2dbd497efa861e0f1c20c
5,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,MO,63401,,1639530496,Nurse/Advanced Practice Nurse,Geriatrics,iamlabocagrande@gmail.com,,MEDSCAPE REGISTRATION,MS,8a6797263d39bea884055deacac7b26968ae939f3cf2dbd497efa861e0f1c20c
6,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,OK,73130,,1639530496,Nurse/Advanced Practice Nurse,Administration/Management,andrea.rae.hunt@gmail.com,,MEDSCAPE REGISTRATION,MS,b0ba99ee6cc8546d23d557b1577f7b6a911160d24ced63ec9de584b83f18ad9c
7,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,OK,73130,,1639530496,Nurse/Advanced Practice Nurse,Diabetes,andrea.rae.hunt@gmail.com,,MEDSCAPE REGISTRATION,MS,b0ba99ee6cc8546d23d557b1577f7b6a911160d24ced63ec9de584b83f18ad9c
8,2026-09-28,medscape,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,ANDREA,HUNT,,,,OK,73130,,1639530496,Nurse/Advanced Practice Nurse,Geriatrics,andrea.rae.hunt@gmail.com,,MEDSCAPE REGISTRATION,MS,b0ba99ee6cc8546d23d557b1577f7b6a911160d24ced63ec9de584b83f18ad9c
9,2026-09-28,stdvendor,2e7813af237f027af9d042e63603eca225aa4d514cfed629dbcd9c95b8d5c5fc,,,,,,,,,1639530496,,,agreen@netsync.net,,quantummedica,QM,94cc560e8e28f7d65ed3519d8c7ab7e68553bbd69577c2163bf6cdd6fc462091

In [44]:
run_query("""
select distinct * from iceberg.onboard.liveintentpii 
where regexp_replace(npi, '^[^_]+_', '') = '1639530496'
and day='2026-09-28'
""")

Query executed in 12.823 seconds

,day,npi,hashedemail
0,2026-09-28,MS_1639530496,8a6797263d39bea884055deacac7b26968ae939f3cf2dbd497efa861e0f1c20c
1,2026-09-28,QM_1639530496,94cc560e8e28f7d65ed3519d8c7ab7e68553bbd69577c2163bf6cdd6fc462091
2,2026-09-28,MS_1639530496,b0ba99ee6cc8546d23d557b1577f7b6a911160d24ced63ec9de584b83f18ad9c
3,2026-09-28,MS_1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e

In [84]:
run_query("""
select * from iceberg.crossscreen.nscreen_ipcollocation_daily_clean where day='2026-09-28' limit 1
""")

Query executed in 3.877 seconds

,day,uid1,uid2,weight,samedevice,differentusers
0,2026-09-28,I5_ID5-5c12xGjyeZvKv0p3N5nfLEQFcAG76aqoNn_KKeU_1g,dbd5c7c0-db23-476e-9055-c3ca8aaa91a9,0.617,False,False

In [ ]:
run_query("""select * from iceberg.crossscreen.nscreen_geo_daily_ua 
where day='2026-09-28' and uid in ('part_tUdyCHSiwZte', '2FFJjfAgFAIq', '389dc412-2bd3-4189-9eb4-c0a1e087ccde') """)

Query executed in 8.245 seconds

          day                uid  geo
0  2026-09-28  part_tUdyCHSiwZte  333

In [52]:
run_query(""" 
WITH matching_emails AS (
    SELECT DISTINCT 
        regexp_extract(npi, '([0-9]{10})$',1) as npi, 
        lower(hashedemail) AS hashedemail
    FROM iceberg.onboard.liveintentpii
    WHERE day = '2026-09-28'
      AND regexp_extract(
          npi,
          '([0-9]{10})$',
          1
      ) = '1639530496'
),

matching_idsync AS (
    SELECT idsync.*, emails.npi as npi
    FROM iceberg.thirdparty.liveintent_idsync idsync
    INNER JOIN matching_emails emails
        ON lower(idsync.hashedemail_sha256) = emails.hashedemail
    WHERE idsync.day = '2026-09-28'
),
matching_uids as (
    SELECT DISTINCT
        day,
        npi,
        liid,
        hashedemail_sha256,
        uid_token,
        split_part(uid_token, ':', 1) AS uid_type,
        split_part(uid_token, ':', 2) AS uid
    FROM matching_idsync
    CROSS JOIN UNNEST(
        split(uids, '|')
    ) AS exploded(uid_token)
    WHERE uid_token <> ''
),
vendor_data as (
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_liveramp_20260928_line_filter_v1_5pct
    union all
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_experian_20260928_line_filter_v1_5pct
    union all
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_throtle_20260928_line_filter_v1_5pct
)
select * 
from matching_uids as mu
left join vendor_data as v
    on mu.uid=v.uid
where matchid is not null
""")

Query executed in 17.326 seconds

,day,npi,liid,hashedemail_sha256,uid_token,uid_type,uid,day,vendor,uid,matchid,householdid,stable
0,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:mGSIKVDm4ctO,98251,mGSIKVDm4ctO,2026-09-28,throtle,mGSIKVDm4ctO,-8807694220336044580,NaN,True
1,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:2FFJjfAgFAIq,98251,2FFJjfAgFAIq,2026-09-28,throtle,2FFJjfAgFAIq,-8807694220336044580,NaN,True
2,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:2FFJjfAgFAIq,98251,2FFJjfAgFAIq,2026-09-28,liveramp,2FFJjfAgFAIq,3597744279521006960,8823308120729131008.000,True
3,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,aaid:14a008b9-4e91-36ea-a873-49f7b5497194,aaid,14a008b9-4e91-36ea-a873-49f7b5497194,2026-09-28,throtle,14a008b9-4e91-36ea-a873-49f7b5497194,-8807694220336044580,NaN,True
4,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:4eAokXU4vO9g,98251,4eAokXU4vO9g,2026-09-28,throtle,4eAokXU4vO9g,-8807694220336044580,NaN,True
5,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:part_Y9joaNRMPsUr,98251,part_Y9joaNRMPsUr,2026-09-28,throtle,part_Y9joaNRMPsUr,-8807694220336044580,NaN,True
6,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:part_tUdyCHSiwZte,98251,part_tUdyCHSiwZte,2026-09-28,throtle,part_tUdyCHSiwZte,-8807694220336044580,NaN,True
7,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:part_tUdyCHSiwZte,98251,part_tUdyCHSiwZte,2026-09-28,experian,part_tUdyCHSiwZte,-5391460821255451246,-6235083072056879104.000,True
8,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:part_tUdyCHSiwZte,98251,part_tUdyCHSiwZte,2026-09-28,liveramp,part_tUdyCHSiwZte,3597744279521006960,8823308120729131008.000,True
9,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,aaid:389dc412-2bd3-4189-9eb4-c0a1e087ccde,aaid,389dc412-2bd3-4189-9eb4-c0a1e087ccde,2026-09-28,liveramp,389dc412-2bd3-4189-9eb4-c0a1e087ccde,3597744279521006960,8823308120729131008.000,True
10,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,98251:Y9joaNRMPsUr,98251,Y9joaNRMPsUr,2026-09-28,throtle,Y9joaNRMPsUr,-8807694220336044580,NaN,True
11,2026-09-28,1639530496,yDpCHcmoBrMFRuM-wiE25z7xPYjPPG2ir2ewrA,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,aaid:c5b7add2-d589-4e9d-b8f1-ca6dec991efb,aaid,c5b7add2-d589-4e9d-b8f1-ca6dec991efb,2026-09-28,liveramp,c5b7add2-d589-4e9d-b8f1-ca6dec991efb,3597744279521006960,8823308120729131008.000,True

In [ ]:
dbfuncs.query2table("""
WITH matching_emails AS (
    SELECT DISTINCT 
        regexp_extract(npi, '^([^_]+)_', 1) as email_source, 
        regexp_extract(npi, '([0-9]{10})$',1) as npi, 
        lower(hashedemail) AS hashedemail
    FROM iceberg.onboard.liveintentpii
    WHERE day = '2026-09-28'
),
matching_pii AS (
    SELECT DISTINCT me.npi, me.email_source, me.hashedemail, first_name, last_name,  state, zip, accountid as pii_source, 
    lower(to_hex(sha256(to_utf8(lower(trim(emails)))))) as pii_hashedemail
    FROM matching_emails me 
    left join iceberg.thirdparty.pii_clean pc
    on me.npi = pc.npi 
        and me.hashedemail=lower(to_hex(sha256(to_utf8(lower(trim(emails))))))
    and pc.day = '2026-09-28'
),
matching_idsync AS (
    SELECT idsync.*, mp.email_source, mp.npi as npi, pii_source, first_name, last_name, state, zip, pii_hashedemail
    FROM iceberg.thirdparty.liveintent_idsync idsync
    INNER JOIN matching_pii mp
        ON lower(idsync.hashedemail_sha256) = mp.hashedemail
    WHERE idsync.day = '2026-09-28'
),
matching_uids as (
    SELECT DISTINCT
        day, email_source,
        npi, pii_source, first_name, last_name, state, zip, pii_hashedemail,
        liid,
        hashedemail_sha256,
        uid_token,
        split_part(uid_token, ':', 1) AS uid_type,
        split_part(uid_token, ':', 2) AS uid
    FROM matching_idsync
    CROSS JOIN UNNEST(
        split(uids, '|')
    ) AS exploded(uid_token)
    WHERE uid_token <> ''
),
vendor_data as (
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_liveramp_20260928_line_filter_v1_5pct
    union all
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_experian_20260928_line_filter_v1_5pct
    union all
    select * from iceberg.jteixeira_ipa.nscreen_membership_sample_throtle_20260928_line_filter_v1_5pct
),
geo_daily_ua as (
    select * from iceberg.crossscreen.nscreen_geo_daily_ua 
    where day='2026-09-28'
),
vendor_uid_evidence as (
    select distinct 
        v.matchid, v.vendor, v.uid, 
        hashedemail_sha256, email_source, npi, pii_source, first_name, last_name, state, zip, pii_hashedemail,
        gdua.geo
    from vendor_data as v
    left join matching_uids as mu
        on mu.uid=v.uid
    left join geo_daily_ua gdua
        on mu.uid=gdua.uid
)
select * from vendor_uid_evidence
""", table_name='tmp_sample_5pct_vendor_uid_evidence_20260928', recreate=True, sort_keys=['matchid'])

Dropping table iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
Query executed in 1.712 seconds
Creating table iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
Query executed in 141.190 seconds

True

In [104]:
run_query("""
select * from iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
where matchid in (3597744279521006960, -8807694220336044580, -5391460821255451246)
order by vendor, matchid, uid
""")

Query executed in 9.053 seconds

,matchid,vendor,uid,hashedemail_sha256,email_source,npi,pii_source,first_name,last_name,state,zip,pii_hashedemail,geo
0,-5391460821255451246,experian,EP_3098108377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-5391460821255451246,experian,TA_797f5b23-eae7-44aa-8200-49860e363ead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-5391460821255451246,experian,TA_8509f4b1-687b-4fb6-859a-ee798a4223dd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-5391460821255451246,experian,TA_d5111b88-2c25-4ebe-b02c-84c67cd14bfc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-5391460821255451246,experian,TA_f0a61c96-106d-42b2-8ec1-8d83579fc7eb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-5391460821255451246,experian,part_tUdyCHSiwZte,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
6,3597744279521006960,liveramp,2FFJjfAgFAIq,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN
7,3597744279521006960,liveramp,389dc412-2bd3-4189-9eb4-c0a1e087ccde,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN
8,3597744279521006960,liveramp,3jzhHSVz08XE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3597744279521006960,liveramp,4aef9d13-8a51-4ea5-a8fd-e305e9521b5d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3597744279521006960,liveramp,4c3d586d-ca0c-4b5e-a3b2-dfb808688d00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3597744279521006960,liveramp,7fe06462-eb42-4ef9-8303-a810f5910845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3597744279521006960,liveramp,9dcef003-0645-4eb1-88a6-ea9cd37427cd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3597744279521006960,liveramp,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3597744279521006960,liveramp,UZ5ugtVuy2eB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,3597744279521006960,liveramp,c5b20593-2b27-4d1b-a0a9-972fa37f544c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3597744279521006960,liveramp,c5b7add2-d589-4e9d-b8f1-ca6dec991efb,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
17,3597744279521006960,liveramp,d0a90931-ed52-4500-9da5-7a8c2b4638f5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3597744279521006960,liveramp,e2614b92-a216-5da1-ab9d-65d8f15f3956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3597744279521006960,liveramp,part_tUdyCHSiwZte,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
20,-8807694220336044580,throtle,14a008b9-4e91-36ea-a873-49f7b5497194,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN
21,-8807694220336044580,throtle,2FFJjfAgFAIq,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN
22,-8807694220336044580,throtle,4eAokXU4vO9g,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
23,-8807694220336044580,throtle,C6ze909cRC5t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,-8807694220336044580,throtle,TH_50557577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,-8807694220336044580,throtle,UZ5ugtVuy2eB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,-8807694220336044580,throtle,Y9joaNRMPsUr,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN
27,-8807694220336044580,throtle,mGSIKVDm4ctO,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
28,-8807694220336044580,throtle,part_Y9joaNRMPsUr,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333
29,-8807694220336044580,throtle,part_tUdyCHSiwZte,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,MS,1639530496,MS,ANDREA,HUNT,FL,33069,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,333

In [140]:
run_query("""
with 
vendor_uid_evidence as (
    select * from iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
    where matchid in (3597744279521006960, -8807694220336044580, -5391460821255451246)
),
uids_list as (
    select distinct uid from vendor_uid_evidence
),
agg_uids as (
    select vendor, matchid, array_agg(uid) arr_uids
    from vendor_uid_evidence
    group by vendor, matchid
),
ipcollocation as (
    select * from iceberg.crossscreen.nscreen_ipcollocation_daily_clean 
    where uid1 in (select uid from uids_list) and uid2 in (select uid from uids_list)
    and day='2026-09-28'
),
merged as (
    select 
        distinct
        v.vendor,
        v.matchid, 
        v.uid, 
        v.geo,
        v.npi,
        v.pii_hashedemail,
        CASE WHEN v.uid=ip.uid1 THEN ip.uid2 ELSE ip.uid1 END as ipcol_uid,
        ip.*,
        au.arr_uids
    from vendor_uid_evidence as v 
    left join ipcollocation as ip
        on v.uid=ip.uid1 or v.uid=ip.uid2
    left join agg_uids au 
        on v.matchid= au.matchid
)
select 
    vendor,
    matchid,
    uid,
    geo,
    npi,
    pii_hashedemail,
    ipcol_uid,
    weight,
    samedevice,
    try_cast(contains(arr_uids, ipcol_uid) AS INTEGER) as ipcoluid_in_matchid
from merged
""")


# select 
#     vendor,
#     matchid, 
#     count(distinct uid) as n_uids, 
#     sum(try_cast(contains(arr_uids, ipcol_uid) AS INTEGER)) as n_uids_ipcol_samematchid
# from merged
# group by vendor, matchid

Query executed in 7.455 seconds

,vendor,matchid,uid,geo,npi,pii_hashedemail,ipcol_uid,weight,samedevice,ipcoluid_in_matchid
0,experian,-5391460821255451246,TA_797f5b23-eae7-44aa-8200-49860e363ead,NaN,NaN,NaN,NaN,NaN,None,NaN
1,liveramp,3597744279521006960,4aef9d13-8a51-4ea5-a8fd-e305e9521b5d,NaN,NaN,NaN,NaN,NaN,None,NaN
2,throtle,-8807694220336044580,part_Y9joaNRMPsUr,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
3,experian,-5391460821255451246,TA_8509f4b1-687b-4fb6-859a-ee798a4223dd,NaN,NaN,NaN,NaN,NaN,None,NaN
4,experian,-5391460821255451246,TA_d5111b88-2c25-4ebe-b02c-84c67cd14bfc,NaN,NaN,NaN,NaN,NaN,None,NaN
5,experian,-5391460821255451246,EP_3098108377,NaN,NaN,NaN,NaN,NaN,None,NaN
6,experian,-5391460821255451246,TA_f0a61c96-106d-42b2-8ec1-8d83579fc7eb,NaN,NaN,NaN,NaN,NaN,None,NaN
7,experian,-5391460821255451246,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,UZ5ugtVuy2eB,0.554,True,0.000
8,experian,-5391460821255451246,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,0.696,True,0.000
9,liveramp,3597744279521006960,e2614b92-a216-5da1-ab9d-65d8f15f3956,NaN,NaN,NaN,NaN,NaN,None,NaN
10,liveramp,3597744279521006960,2FFJjfAgFAIq,NaN,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
11,liveramp,3597744279521006960,4c3d586d-ca0c-4b5e-a3b2-dfb808688d00,NaN,NaN,NaN,NaN,NaN,None,NaN
12,liveramp,3597744279521006960,3jzhHSVz08XE,NaN,NaN,NaN,NaN,NaN,None,NaN
13,liveramp,3597744279521006960,7fe06462-eb42-4ef9-8303-a810f5910845,NaN,NaN,NaN,NaN,NaN,None,NaN
14,liveramp,3597744279521006960,389dc412-2bd3-4189-9eb4-c0a1e087ccde,NaN,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
15,liveramp,3597744279521006960,d0a90931-ed52-4500-9da5-7a8c2b4638f5,NaN,NaN,NaN,NaN,NaN,None,NaN
16,liveramp,3597744279521006960,9dcef003-0645-4eb1-88a6-ea9cd37427cd,NaN,NaN,NaN,NaN,NaN,None,NaN
17,liveramp,3597744279521006960,c5b7add2-d589-4e9d-b8f1-ca6dec991efb,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
18,liveramp,3597744279521006960,UZ5ugtVuy2eB,NaN,NaN,NaN,part_tUdyCHSiwZte,0.554,True,1.000
19,liveramp,3597744279521006960,UZ5ugtVuy2eB,NaN,NaN,NaN,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,2.496,True,1.000
20,liveramp,3597744279521006960,c5b20593-2b27-4d1b-a0a9-972fa37f544c,NaN,NaN,NaN,NaN,NaN,None,NaN
21,liveramp,3597744279521006960,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,NaN,NaN,NaN,UZ5ugtVuy2eB,2.496,True,1.000
22,liveramp,3597744279521006960,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,NaN,NaN,NaN,part_tUdyCHSiwZte,0.696,True,1.000
23,liveramp,3597744279521006960,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,UZ5ugtVuy2eB,0.554,True,1.000
24,liveramp,3597744279521006960,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,0.696,True,1.000
25,throtle,-8807694220336044580,TH_50557577,NaN,NaN,NaN,NaN,NaN,None,NaN
26,throtle,-8807694220336044580,2FFJjfAgFAIq,NaN,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
27,throtle,-8807694220336044580,mGSIKVDm4ctO,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
28,throtle,-8807694220336044580,4eAokXU4vO9g,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
29,throtle,-8807694220336044580,Y9joaNRMPsUr,NaN,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
30,throtle,-8807694220336044580,UZ5ugtVuy2eB,NaN,NaN,NaN,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,2.496,True,0.000
31,throtle,-8807694220336044580,UZ5ugtVuy2eB,NaN,NaN,NaN,part_tUdyCHSiwZte,0.554,True,1.000
32,throtle,-8807694220336044580,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,LR_XY4118wOhgOsMvP4pxZW-CbuUGFk7oeLzRRJDFQgp1tBKXPTo,0.696,True,0.000
33,throtle,-8807694220336044580,14a008b9-4e91-36ea-a873-49f7b5497194,NaN,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,NaN,NaN,None,NaN
34,throtle,-8807694220336044580,C6ze909cRC5t,NaN,NaN,NaN,NaN,NaN,None,NaN
35,throtle,-8807694220336044580,part_tUdyCHSiwZte,333,1639530496,0d3a00d5ff4b660ab0fe03897edd4be8f94a19bf8b4f4e778a561bce9270012e,UZ5ugtVuy2eB,0.554,True,1.000

In [ ]:
run_query("""
with 
vendor_uid_evidence as (
    select * from iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
    where matchid in (3597744279521006960, -8807694220336044580, -5391460821255451246)
),
uids_list as (
    select distinct uid from vendor_uid_evidence
),
agg_uids as (
    select vendor, matchid, array_agg(uid) arr_uids
    from vendor_uid_evidence
    group by vendor, matchid
),
ipcollocation as (
    select * from iceberg.crossscreen.nscreen_ipcollocation_daily_clean 
    where uid1 in (select uid from uids_list) and uid2 in (select uid from uids_list)
    and day='2026-09-28'
),
merged as (
    select 
        distinct
        v.vendor,
        v.matchid, 
        v.uid, 
        v.geo,
        v.npi,
        v.pii_hashedemail,
        CASE WHEN v.uid=ip.uid1 THEN ip.uid2 ELSE ip.uid1 END as ipcol_uid,
        ip.*,
        au.arr_uids
    from vendor_uid_evidence as v 
    left join ipcollocation as ip
        on v.uid=ip.uid1 or v.uid=ip.uid2
    left join agg_uids au 
        on v.matchid= au.matchid
)
select 
    vendor,
    matchid, 
    count(distinct uid) as n_uids, 
    count(distinct geo) as n_zip3,
    count(distinct npi) as n_npi,
    count(distinct pii_hashedemail) as n_emails,
    count(distinct case when pii_hashedemail is not null then uid end) as n_uids_email_link,
    count(distinct ipcol_uid) as n_ipcol_uids,
    sum(coalesce(weight, 0.0)) as sum_weight,
    count(distinct case when ipcol_uid is not null then uid end) as n_uids_in_ipcol,
    count(distinct case when contains(arr_uids, ipcol_uid) then uid end) as n_uids_w_ipcol_samematchid
from merged
group by vendor, matchid
""")

Query executed in 74.442 seconds

,vendor,matchid,n_uids,n_geo,n_npi,n_emails,n_uids_email_link,n_ipcol_uids,sum_weight,n_uids_in_ipcol,n_uids_w_ipcol_samematchid
0,liveramp,3597744279521006960,14,1,1,1,4,3,7.493,3,3
1,experian,-5391460821255451246,6,1,1,1,1,2,1.250,1,0
2,throtle,-8807694220336044580,10,1,1,1,7,3,4.300,2,2

In [ ]:
df=run_query("""
with 
matchids_nuids as (
    select matchid, count(distinct uid) as n_uids 
    from iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
    group by matchid
),
sample_matchid as (
    select matchid from matchids_nuids where n_uids>1
    limit 100
),
vendor_uid_evidence as (
    select * from iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
    where matchid in (select matchid from sample_matchid)
),
uids_list as (
    select distinct uid from vendor_uid_evidence
),
agg_uids as (
    select vendor, matchid, array_agg(uid) arr_uids
    from vendor_uid_evidence
    group by vendor, matchid
),
ipcollocation as (
    select * from iceberg.crossscreen.nscreen_ipcollocation_daily_clean 
    where uid1 in (select uid from uids_list) and uid2 in (select uid from uids_list)
    and day='2026-09-28'
),
merged as (
    select 
        distinct
        v.vendor,
        v.matchid, 
        v.uid, 
        v.geo,
        v.npi,
        v.pii_hashedemail,
        CASE WHEN v.uid=ip.uid1 THEN ip.uid2 ELSE ip.uid1 END as ipcol_uid,
        ip.*,
        au.arr_uids
    from vendor_uid_evidence as v 
    left join ipcollocation as ip
        on v.uid=ip.uid1 or v.uid=ip.uid2
    left join agg_uids au 
        on v.matchid= au.matchid
)
select 
    vendor,
    matchid, 
    count(distinct uid) as n_uids, 
    count(distinct geo) as n_geo,
    count(distinct npi) as n_npi,
    count(distinct pii_hashedemail) as n_emails,
    count(distinct case when pii_hashedemail is not null then uid end) as n_uids_email_link,
    count(distinct ipcol_uid) as n_ipcol_uids,
    sum(coalesce(weight, 0.0)) as sum_weight,
    count(distinct case when ipcol_uid is not null then uid end) as n_uids_in_ipcol,
    count(distinct case when contains(arr_uids, ipcol_uid) then uid end) as n_uids_w_ipcol_samematchid
from merged
group by vendor, matchid
""")

Query executed in 27.045 seconds

In [180]:
df

,vendor,matchid,n_uids,n_geo,n_npi,n_emails,n_uids_email_link,n_ipcol_uids,sum_weight,n_uids_in_ipcol,n_uids_w_ipcol_samematchid
0,liveramp,-7520968143929373389,52,0,0,0,0,0,0.000,0,0
1,liveramp,-8970121116132125832,28,0,0,0,0,0,0.000,0,0
2,liveramp,5730102798354826235,28,0,1,1,1,0,0.000,0,0
3,liveramp,-8461241829865155830,40,0,0,0,0,0,0.000,0,0
4,liveramp,7733897493184634864,30,0,0,0,0,0,0.000,0,0
...,...,...,...,...,...,...,...,...,...,...,...
99995,throtle,5160639103375888860,2,0,0,0,0,0,0.000,0,0
99996,liveramp,3465958965011565900,2,0,0,0,0,0,0.000,0,0
99997,throtle,4385475654375761633,2,0,0,0,0,0,0.000,0,0
99998,throtle,-51417639834409419,2,0,0,0,0,0,0.000,0,0
99999,throtle,868773882653017680,2,0,0,0,0,0,0.000,0,0

## Bucketed local matchid metrics

Hive publication is unavailable, so this section computes final metrics through read-only Trino queries and writes one local Parquet file per deterministic `(vendor, matchid)` bucket.

Every identity group remains inside one bucket. The eligible UID universe remains global so collocation links to eligible UIDs in other buckets are preserved. Existing bucket files are reused, which makes interrupted runs resumable.

In [193]:
METRICS_DAY = "2026-09-28"
BUCKET_COUNT = 32
OVERWRITE_BUCKETS = False
BUCKET_OUTPUT_DIR = (
    Path("output/vendor_cookie_crossvalidation/matchid_metrics_20260928")
    / f"buckets_{BUCKET_COUNT:03d}"
)
BUCKET_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Bucket count: {BUCKET_COUNT}")
print(f"Local output: {BUCKET_OUTPUT_DIR.resolve()}")

Bucket count: 32
Local output: /Users/jteixeira/nscreen_analysis/vendor_quality_measurement/output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032

In [194]:
def build_matchid_metrics_sql(bucket: int, bucket_count: int) -> str:
    # Build one read-only metrics query for one deterministic group bucket.
    if bucket_count <= 0:
        raise ValueError("bucket_count must be positive")
    if not 0 <= bucket < bucket_count:
        raise ValueError("bucket must satisfy 0 <= bucket < bucket_count")

    return f"""
WITH eligible_groups AS (
    SELECT
        vendor,
        matchid
    FROM iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928
    WHERE uid IS NOT NULL
    GROUP BY
        vendor,
        matchid
    HAVING count(DISTINCT uid) > 1
),

bucket_groups AS (
    SELECT
        vendor,
        matchid
    FROM eligible_groups
    WHERE mod(
        crc32(
            to_utf8(
                concat(vendor, ':', cast(matchid AS varchar))
            )
        ),
        {bucket_count}
    ) = {bucket}
),

bucket_members AS (
    SELECT DISTINCT
        e.vendor,
        e.matchid,
        e.uid
    FROM iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928 e
    JOIN bucket_groups g
      ON e.vendor = g.vendor
     AND e.matchid = g.matchid
    WHERE e.uid IS NOT NULL
),

bucket_uid_universe AS (
    SELECT DISTINCT uid
    FROM bucket_members
),

global_uid_universe AS (
    SELECT DISTINCT e.uid
    FROM iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928 e
    JOIN eligible_groups g
      ON e.vendor = g.vendor
     AND e.matchid = g.matchid
    WHERE e.uid IS NOT NULL
),

ip_neighbors AS (
    SELECT DISTINCT
        ip.uid1 AS uid,
        ip.uid2 AS ipcol_uid,
        ip.weight,
        ip.samedevice
    FROM iceberg.crossscreen.nscreen_ipcollocation_daily_clean ip
    JOIN bucket_uid_universe source_uid
      ON ip.uid1 = source_uid.uid
    JOIN global_uid_universe neighbor_uid
      ON ip.uid2 = neighbor_uid.uid
    WHERE ip.day = '{METRICS_DAY}'

    UNION

    SELECT DISTINCT
        ip.uid2 AS uid,
        ip.uid1 AS ipcol_uid,
        ip.weight,
        ip.samedevice
    FROM iceberg.crossscreen.nscreen_ipcollocation_daily_clean ip
    JOIN bucket_uid_universe source_uid
      ON ip.uid2 = source_uid.uid
    JOIN global_uid_universe neighbor_uid
      ON ip.uid1 = neighbor_uid.uid
    WHERE ip.day = '{METRICS_DAY}'
),

evidence_metrics AS (
    SELECT
        s.vendor,
        s.matchid,
        count(DISTINCT s.uid) AS n_uids,
        count(DISTINCT e.geo) AS n_geo,
        count(DISTINCT e.npi) AS n_npi,
        count(DISTINCT e.pii_hashedemail) AS n_emails,
        count(
            DISTINCT CASE
                WHEN e.pii_hashedemail IS NOT NULL
                THEN s.uid
            END
        ) AS n_uids_email_link
    FROM bucket_members s
    LEFT JOIN iceberg.jteixeira_ipa.tmp_sample_5pct_vendor_uid_evidence_20260928 e
      ON s.vendor = e.vendor
     AND s.matchid = e.matchid
     AND s.uid = e.uid
    GROUP BY
        s.vendor,
        s.matchid
),

collocation_metrics AS (
    SELECT
        s.vendor,
        s.matchid,
        count(DISTINCT n.ipcol_uid) AS n_ipcol_uids,
        coalesce(sum(n.weight), 0.0) AS sum_weight,
        count(
            DISTINCT CASE
                WHEN n.ipcol_uid IS NOT NULL
                THEN s.uid
            END
        ) AS n_uids_in_ipcol,
        count(
            DISTINCT CASE
                WHEN peer.uid IS NOT NULL
                THEN s.uid
            END
        ) AS n_uids_w_ipcol_samematchid
    FROM bucket_members s
    LEFT JOIN ip_neighbors n
      ON s.uid = n.uid
    LEFT JOIN bucket_members peer
      ON s.vendor = peer.vendor
     AND s.matchid = peer.matchid
     AND n.ipcol_uid = peer.uid
    GROUP BY
        s.vendor,
        s.matchid
)

SELECT
    e.vendor,
    e.matchid,
    e.n_uids,
    e.n_geo,
    e.n_npi,
    e.n_emails,
    e.n_uids_email_link,
    coalesce(c.n_ipcol_uids, 0) AS n_ipcol_uids,
    coalesce(c.sum_weight, 0.0) AS sum_weight,
    coalesce(c.n_uids_in_ipcol, 0) AS n_uids_in_ipcol,
    coalesce(
        c.n_uids_w_ipcol_samematchid,
        0
    ) AS n_uids_w_ipcol_samematchid
FROM evidence_metrics e
LEFT JOIN collocation_metrics c
  ON e.vendor = c.vendor
 AND e.matchid = c.matchid
"""

In [195]:
bucket_runs = []

for bucket in range(BUCKET_COUNT):
    bucket_path = BUCKET_OUTPUT_DIR / f"bucket={bucket:03d}.parquet"

    if bucket_path.exists() and not OVERWRITE_BUCKETS:
        bucket_runs.append(
            {
                "bucket": bucket,
                "status": "reused",
                "rows": len(pd.read_parquet(bucket_path, columns=["matchid"])),
                "path": str(bucket_path),
            }
        )
        continue

    bucket_frame = run_query(
        build_matchid_metrics_sql(bucket, BUCKET_COUNT)
    )
    duplicate_groups = bucket_frame.duplicated(
        ["vendor", "matchid"]
    ).sum()
    if duplicate_groups:
        raise RuntimeError(
            f"Bucket {bucket} contains {duplicate_groups} duplicate groups"
        )

    temporary_path = bucket_path.with_suffix(".parquet.tmp")
    bucket_frame.to_parquet(temporary_path, index=False)
    temporary_path.replace(bucket_path)
    bucket_runs.append(
        {
            "bucket": bucket,
            "status": "queried",
            "rows": len(bucket_frame),
            "path": str(bucket_path),
        }
    )

bucket_status = pd.DataFrame(bucket_runs)
display(bucket_status)

Query executed in 701.399 seconds
Query executed in 60.872 seconds
Query executed in 52.753 seconds
Query executed in 48.721 seconds
Query executed in 51.314 seconds
Query executed in 55.676 seconds
Query executed in 48.578 seconds
Query executed in 43.754 seconds
Query executed in 49.186 seconds
Query executed in 45.322 seconds
Query executed in 47.763 seconds
Query executed in 42.331 seconds
Query executed in 44.849 seconds
Query executed in 66.715 seconds
Query executed in 46.785 seconds
Query executed in 44.291 seconds
Query executed in 46.208 seconds
Query executed in 49.302 seconds
Query executed in 52.851 seconds
Query executed in 46.202 seconds
Query executed in 48.352 seconds
Query executed in 46.295 seconds
Query executed in 44.326 seconds
Query executed in 44.825 seconds
Query executed in 44.282 seconds
Query executed in 44.425 seconds
Query executed in 50.376 seconds
Query executed in 47.939 seconds
Query executed in 46.173 seconds
Query executed in 44.163 seconds
Query executed in 44.855 seconds
Query executed in 50.870 seconds

,bucket,status,rows,path
0,0,queried,470003,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=000.parquet
1,1,queried,468087,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=001.parquet
2,2,queried,467322,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=002.parquet
3,3,queried,467731,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=003.parquet
4,4,queried,467717,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=004.parquet
5,5,queried,467797,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=005.parquet
6,6,queried,467405,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=006.parquet
7,7,queried,468583,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=007.parquet
8,8,queried,468926,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=008.parquet
9,9,queried,468326,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=009.parquet
10,10,queried,468112,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=010.parquet
11,11,queried,469759,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=011.parquet
12,12,queried,468434,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=012.parquet
13,13,queried,468463,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=013.parquet
14,14,queried,467450,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=014.parquet
15,15,queried,467969,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=015.parquet
16,16,queried,466734,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=016.parquet
17,17,queried,467644,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=017.parquet
18,18,queried,467050,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=018.parquet
19,19,queried,467648,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=019.parquet
20,20,queried,468290,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=020.parquet
21,21,queried,467788,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=021.parquet
22,22,queried,467374,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=022.parquet
23,23,queried,468554,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=023.parquet
24,24,queried,466589,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=024.parquet
25,25,queried,468167,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=025.parquet
26,26,queried,468116,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=026.parquet
27,27,queried,468469,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=027.parquet
28,28,queried,467469,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=028.parquet
29,29,queried,467613,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=029.parquet
30,30,queried,468020,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=030.parquet
31,31,queried,466955,output/vendor_cookie_crossvalidation/matchid_metrics_20260928/buckets_032/bucket=031.parquet

In [196]:
bucket_files = sorted(BUCKET_OUTPUT_DIR.glob("bucket=*.parquet"))
completed_buckets = {
    int(path.stem.split("=")[1])
    for path in bucket_files
}
missing_buckets = sorted(set(range(BUCKET_COUNT)) - completed_buckets)

if missing_buckets:
    raise RuntimeError(f"Missing bucket files: {missing_buckets}")

df = pd.concat(
    (pd.read_parquet(path) for path in bucket_files),
    ignore_index=True,
)

expected_columns = [
    "vendor",
    "matchid",
    "n_uids",
    "n_geo",
    "n_npi",
    "n_emails",
    "n_uids_email_link",
    "n_ipcol_uids",
    "sum_weight",
    "n_uids_in_ipcol",
    "n_uids_w_ipcol_samematchid",
]
if df.columns.tolist() != expected_columns:
    raise RuntimeError(
        f"Unexpected columns: {df.columns.tolist()}"
    )
if df.duplicated(["vendor", "matchid"]).any():
    raise RuntimeError("Duplicate (vendor, matchid) groups found")

df = df.sort_values(["vendor", "matchid"]).reset_index(drop=True)
pd.DataFrame(
    {
        "bucket_files": [len(bucket_files)],
        "metric_rows": [len(df)],
        "duplicate_groups": [0],
    }
)

   bucket_files  metric_rows  duplicate_groups
0            32     14974564                 0

In [198]:
df.loc[
    (df["n_npi"] >= 10)
    & (df["n_uids_in_ipcol"] >= 1)
].head(100)

,vendor,matchid,n_uids,n_geo,n_npi,n_emails,n_uids_email_link,n_ipcol_uids,sum_weight,n_uids_in_ipcol,n_uids_w_ipcol_samematchid
6990489,liveramp,-1929459330674946534,48,1,14,1,1,6,51.629,6,6
10599622,liveramp,6699883859400941031,47,1,16,1,9,3,12.707,3,3

In [200]:
# Publish matching server-side bucket queries into one resumable Trino table.
import pyarrow.parquet as pq

TRINO_TARGET_NAME = "tmp_sample_5pct_matchid_metrics_20260928"
TRINO_TARGET_SCHEMA = "iceberg.jteixeira_ipa"
TRINO_TARGET = f"{TRINO_TARGET_SCHEMA}.{TRINO_TARGET_NAME}"
TRINO_WRITER_SESSION = {
    "max_writer_task_count": "8",
    "task_max_writer_count": "1",
}

EXPECTED_TRINO_COLUMNS = [
    "vendor",
    "matchid",
    "n_uids",
    "n_geo",
    "n_npi",
    "n_emails",
    "n_uids_email_link",
    "n_ipcol_uids",
    "sum_weight",
    "n_uids_in_ipcol",
    "n_uids_w_ipcol_samematchid",
]

expected_bucket_rows = {
    bucket: pq.ParquetFile(
        BUCKET_OUTPUT_DIR / f"bucket={bucket:03d}.parquet"
    ).metadata.num_rows
    for bucket in range(BUCKET_COUNT)
}
expected_total_rows = sum(expected_bucket_rows.values())


def trino_bucket_expression() -> str:
    return f"""
        mod(
            crc32(
                to_utf8(
                    concat(vendor, ':', cast(matchid AS varchar))
                )
            ),
            {BUCKET_COUNT}
        )
    """


def read_remote_bucket_counts() -> dict[int, int]:
    frame = dbfuncs.query2df(
        f"""
        SELECT
            {trino_bucket_expression()} AS bucket,
            count(*) AS row_count
        FROM {TRINO_TARGET}
        GROUP BY 1
        ORDER BY 1
        """,
        print_time=False,
    )
    return {
        int(row.bucket): int(row.row_count)
        for row in frame.itertuples(index=False)
    }


def read_remote_bucket_count(bucket: int) -> int:
    frame = dbfuncs.query2df(
        f"""
        SELECT count(*) AS row_count
        FROM {TRINO_TARGET}
        WHERE {trino_bucket_expression()} = {bucket}
        """,
        print_time=False,
    )
    return int(frame.iloc[0, 0])


def validate_trino_schema() -> None:
    description = dbfuncs.query2df(
        f"DESCRIBE {TRINO_TARGET}",
        print_time=False,
    )
    actual_columns = description.iloc[:, 0].tolist()
    if actual_columns != EXPECTED_TRINO_COLUMNS:
        raise RuntimeError(
            "Unexpected target columns: "
            f"expected {EXPECTED_TRINO_COLUMNS}, found {actual_columns}"
        )


if not dbfuncs.table_exists(
    TRINO_TARGET_NAME,
    catalog_schema=TRINO_TARGET_SCHEMA,
):
    try:
        dbfuncs.query2table(
            build_matchid_metrics_sql(0, BUCKET_COUNT),
            TRINO_TARGET_NAME,
            catalog_schema=TRINO_TARGET_SCHEMA,
            session_properties=TRINO_WRITER_SESSION,
        )
    except Exception:
        if not dbfuncs.table_exists(
            TRINO_TARGET_NAME,
            catalog_schema=TRINO_TARGET_SCHEMA,
        ):
            raise

validate_trino_schema()
remote_bucket_rows = read_remote_bucket_counts()
publication_runs = []

for bucket in range(BUCKET_COUNT):
    expected_rows = expected_bucket_rows[bucket]
    remote_rows = remote_bucket_rows.get(bucket, 0)

    if remote_rows == expected_rows:
        publication_runs.append(
            {
                "bucket": bucket,
                "status": "already_committed",
                "rows": remote_rows,
            }
        )
        continue
    if remote_rows != 0:
        raise RuntimeError(
            f"Bucket {bucket} contains {remote_rows:,} rows; "
            f"expected 0 or {expected_rows:,}"
        )

    try:
        dbfuncs.query2table(
            build_matchid_metrics_sql(bucket, BUCKET_COUNT),
            TRINO_TARGET_NAME,
            catalog_schema=TRINO_TARGET_SCHEMA,
            insert=True,
            session_properties=TRINO_WRITER_SESSION,
        )
    except Exception:
        committed_rows = read_remote_bucket_count(bucket)
        if committed_rows != expected_rows:
            raise

    committed_rows = read_remote_bucket_count(bucket)
    if committed_rows != expected_rows:
        raise RuntimeError(
            f"Bucket {bucket} committed {committed_rows:,} rows; "
            f"expected {expected_rows:,}"
        )
    remote_bucket_rows[bucket] = committed_rows
    publication_runs.append(
        {
            "bucket": bucket,
            "status": "inserted",
            "rows": committed_rows,
        }
    )

trino_validation = dbfuncs.query2df(
    f"""
    SELECT
        count(*) AS row_count,
        count(DISTINCT ROW(vendor, matchid)) AS distinct_groups
    FROM {TRINO_TARGET}
    """,
    print_time=True,
)
published_rows = int(trino_validation.loc[0, "row_count"])
distinct_groups = int(trino_validation.loc[0, "distinct_groups"])

if published_rows != expected_total_rows:
    raise RuntimeError(
        f"Expected {expected_total_rows:,} rows, found {published_rows:,}"
    )
if distinct_groups != published_rows:
    raise RuntimeError(
        f"Found {published_rows - distinct_groups:,} duplicate groups"
    )

publication_status = pd.DataFrame(publication_runs)
display(publication_status)
trino_validation

Query executed in 3.121 seconds

    bucket             status    rows
0        0  already_committed  470003
1        1  already_committed  468087
2        2  already_committed  467322
3        3  already_committed  467731
4        4  already_committed  467717
5        5  already_committed  467797
6        6  already_committed  467405
7        7  already_committed  468583
8        8  already_committed  468926
9        9  already_committed  468326
10      10  already_committed  468112
11      11  already_committed  469759
12      12  already_committed  468434
13      13  already_committed  468463
14      14  already_committed  467450
15      15  already_committed  467969
16      16  already_committed  466734
17      17  already_committed  467644
18      18  already_committed  467050
19      19  already_committed  467648
20      20  already_committed  468290
21      21  already_committed  467788
22      22  already_committed  467374
23      23  already_committed  468554
24      24  already_committed  466589
25      25  already_committed  468167
26      26  already_committed  468116
27      27  already_committed  468469
28      28  already_committed  467469
29      29  already_committed  467613
30      30  already_committed  468020
31      31  already_committed  466955

   row_count  distinct_groups
0   14974564         14974564

In [ ]:
run_query(
    """
select * from iceberg.jteixeira_ipa.tmp_sample_5pct_matchid_metrics_20260928
where n_npi>=10 limit 100"""
)

## Column dictionary: local matchid metrics

### Row grain and scope

Each row describes one `(vendor, matchid)` identity group containing more than one distinct UID. Inputs are the 5% vendor-membership sample plus PII, geo, and IP-collocation evidence dated `2026-09-28`.

Bucket assignment hashes both `vendor` and `matchid`. This preserves the logical group key even when different vendors reuse the same `matchid`. The global eligible UID universe is evaluated inside every query, while only target groups are bucketed.

| Column | What it represents |
|---|---|
| `vendor` | Source identity vendor, such as LiveRamp, Experian, or Throtle. |
| `matchid` | Vendor-supplied identity-cluster identifier. Use `(vendor, matchid)` as the logical key. |
| `n_uids` | Distinct vendor UIDs assigned to the group. |
| `n_geo` | Distinct non-null `geo` values linked to group UIDs. |
| `n_npi` | Distinct NPI identifiers linked through the LiveIntent email and ID-sync path. |
| `n_emails` | Distinct non-null hashed email values linked to group UIDs. |
| `n_uids_email_link` | Distinct group UIDs having at least one non-null `pii_hashedemail`. |
| `n_ipcol_uids` | Distinct eligible neighbor UIDs connected through IP-collocation edges. Neighbors may belong to other groups or buckets. |
| `sum_weight` | Sum of deduplicated directional collocation weights joined to group members. An internal edge contributes once for each member endpoint. |
| `n_uids_in_ipcol` | Distinct group UIDs participating in at least one eligible collocation edge. |
| `n_uids_w_ipcol_samematchid` | Distinct group UIDs having at least one collocated neighbor inside the same `(vendor, matchid)` group. |

### Output behavior

- Each bucket writes one Parquet file under `BUCKET_OUTPUT_DIR`.
- Existing files are reused when `OVERWRITE_BUCKETS` is `False`.
- Final assembly requires every configured bucket.
- Validation rejects duplicate `(vendor, matchid)` rows.
- `BUCKET_COUNT` selects a separate local output directory.
- The publication cell reruns matching bucket queries server-side; local Parquet files provide expected row counts.
- Existing complete Trino buckets are skipped, making publication resumable.
- Partially populated Trino buckets stop publication before further writes.